name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout rsm
        uses: actions/checkout@v4
        with:
          repository: ricedotwho/rsmodern
          token: ${{ secrets.GITHUB_TOKEN }}
          path: rsmodern

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make gradle wrapper executable (rsm)
        run: chmod +x ./project-b/gradlew

      - name: Build and install rsm to mavenLocal
        run: ./rsmodern/gradlew publishToMavenLocal

      - name: Checkout this
        uses: actions/checkout@v4
        with:
          path: project-a

      - name: Make gradle wrapper executable (this)
        run: chmod +x ./gradlew

      - name: Build this
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/